export const gigData = [
  { "title": "Web Design", "views": 1250, "orders": 34, "earning": 10200, "status": "active" },
  { "title": "UI/UX", "views": 980, "orders": 28, "earning": 8400, "status": "approval waiting" },
  { "title": "App Development", "views": 1500, "orders": 40, "earning": 16000, "status": "active" },
  { "title": "Logo Design", "views": 700, "orders": 18, "earning": 3600, "status": "approval waiting" },
  { "title": "Frontend Development", "views": 1100, "orders": 25, "earning": 7500, "status": "active" },
  { "title": "Backend Development", "views": 900, "orders": 20, "earning": 9000, "status": "active" },
  { "title": "E-commerce Setup", "views": 1300, "orders": 31, "earning": 12400, "status": "approval waiting" },
  { "title": "SEO Optimization", "views": 800, "orders": 19, "earning": 3800, "status": "active" },
  { "title": "Landing Page Design", "views": 600, "orders": 15, "earning": 3000, "status": "approval waiting" },
  { "title": "Website Redesign", "views": 1050, "orders": 23, "earning": 6900, "status": "active" },
  { "title": "Mobile UI Design", "views": 720, "orders": 17, "earning": 5100, "status": "approval waiting" },
  { "title": "Dashboard Design", "views": 950, "orders": 22, "earning": 8800, "status": "active" },
  { "title": "WordPress Setup", "views": 1400, "orders": 37, "earning": 11100, "status": "approval waiting" },
  { "title": "ReactJS Development", "views": 1600, "orders": 42, "earning": 16800, "status": "active" },
  { "title": "Graphic Design", "views": 670, "orders": 14, "earning": 2800, "status": "approval waiting" },
  { "title": "Portfolio Website", "views": 850, "orders": 21, "earning": 6300, "status": "active" },
  { "title": "Website Maintenance", "views": 550, "orders": 12, "earning": 2400, "status": "approval waiting" },
  { "title": "Blog Setup", "views": 790, "orders": 16, "earning": 3200, "status": "active" },
  { "title": "API Integration", "views": 1000, "orders": 26, "earning": 10400, "status": "approval waiting" },
  { "title": "Custom Web App", "views": 1750, "orders": 45, "earning": 18000, "status": "active" }
]
export const orderData = [
  { "title": "Web Design", "orderId": "#48392", "status": "Active", "payment": 1200 },
  { "title": "UI/UX", "orderId": "#59281", "status": "Completed", "payment": "pending" },
  { "title": "App Development", "orderId": "#38271", "status": "Completed", "payment": 3200 },
  { "title": "Logo Design", "orderId": "#14829", "status": "Active", "payment": "pending" },
  { "title": "Frontend Development", "orderId": "#98421", "status": "Completed", "payment": 850 },
  { "title": "Backend Development", "orderId": "#23918", "status": "Active", "payment": 1900 },
  { "title": "E-commerce Setup", "orderId": "#82190", "status": "Completed", "payment": 2400 },
  { "title": "SEO Optimization", "orderId": "#47320", "status": "Active", "payment": "pending" },
  { "title": "Landing Page Design", "orderId": "#91283", "status": "Completed", "payment": 600 },
  { "title": "Website Redesign", "orderId": "#59438", "status": "Active", "payment": 1700 },
  { "title": "Mobile UI Design", "orderId": "#71549", "status": "Completed", "payment": 950 },
  { "title": "Dashboard Design", "orderId": "#62415", "status": "Active", "payment": "pending" },
  { "title": "WordPress Setup", "orderId": "#30294", "status": "Completed", "payment": 2100 },
  { "title": "ReactJS Development", "orderId": "#39185", "status": "Active", "payment": 2750 },
  { "title": "Graphic Design", "orderId": "#64823", "status": "Completed", "payment": "pending" },
  { "title": "Portfolio Website", "orderId": "#71935", "status": "Completed", "payment": 1250 },
  { "title": "Website Maintenance", "orderId": "#82374", "status": "Active", "payment": "pending" },
  { "title": "Blog Setup", "orderId": "#91620", "status": "Completed", "payment": 700 },
  { "title": "API Integration", "orderId": "#37162", "status": "Active", "payment": 1800 },
  { "title": "Custom Web App", "orderId": "#58401", "status": "Completed", "payment": 3300 }
]
export const earningData = [
  { "date": "11 Jan", "job": "Web Design", "amount": 1200, "status": "Withdrawn" },
  { "date": "15 Feb", "job": "UI/UX", "amount": 950, "status": "Pending" },
  { "date": "03 Mar", "job": "App Development", "amount": 3200, "status": "Withdrawn" },
  { "date": "20 Apr", "job": "Logo Design", "amount": 400, "status": "Pending" },
  { "date": "25 Jan", "job": "Frontend Development", "amount": 1000, "status": "Withdrawn" },
  { "date": "07 Feb", "job": "Backend Development", "amount": 1600, "status": "Pending" },
  { "date": "11 Mar", "job": "E-commerce Setup", "amount": 2100, "status": "Withdrawn" },
  { "date": "19 Apr", "job": "SEO Optimization", "amount": 650, "status": "Pending" },
  { "date": "30 Jan", "job": "Landing Page Design", "amount": 720, "status": "Withdrawn" },
  { "date": "05 Feb", "job": "Website Redesign", "amount": 1850, "status": "Withdrawn" },
  { "date": "13 Mar", "job": "Mobile UI Design", "amount": 900, "status": "Pending" },
  { "date": "21 Apr", "job": "Dashboard Design", "amount": 1300, "status": "Withdrawn" },
  { "date": "08 Jan", "job": "WordPress Setup", "amount": 1950, "status": "Withdrawn" },
  { "date": "14 Feb", "job": "ReactJS Development", "amount": 2900, "status": "Pending" },
  { "date": "26 Mar", "job": "Graphic Design", "amount": 500, "status": "Withdrawn" },
  { "date": "17 Apr", "job": "Portfolio Website", "amount": 1450, "status": "Pending" },
  { "date": "22 Jan", "job": "Website Maintenance", "amount": 750, "status": "Withdrawn" },
  { "date": "06 Feb", "job": "Blog Setup", "amount": 870, "status": "Pending" },
  { "date": "09 Mar", "job": "API Integration", "amount": 1600, "status": "Withdrawn" },
  { "date": "29 Apr", "job": "Custom Web App", "amount": 3400, "status": "Pending" }
]